# Generated by Django 4.1.7 on 2023-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('content', models.TextField()),
            ],
        ),
    ]
