# Generated by Django 4.1.7 on 2024-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_testprogram_testprogramtopic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testprogram",
            name="priority_in_major_programs_list",
            field=models.IntegerField(
                choices=[
                    (0, "Do not display on homepage"),
                    (1, "Display in first column"),
                    (2, "Display in second column"),
                    (3, "Display in third column"),
                ],
                default=0,
                help_text="Choose 0 if you don't want this program to display in homepage, else choose 1, 2, or 3 priority",
            ),
        ),
        migrations.AlterField(
            model_name="testprogram",
            name="readtime",
            field=models.CharField(
                help_text="Expected Read Time of this Blog, like '5 mins'",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="testprogramtopic",
            name="topic_detail_first_img_caption",
            field=models.CharField(
                blank=True,
                help_text="Write caption for the image in less than 500 characters",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testprogramtopic",
            name="topic_detail_first_video_embed_source",
            field=models.CharField(
                blank=True,
                help_text="Write the source of the video you want to embed. See the 'src' under iframe tag",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testprogramtopic",
            name="topic_detail_second_img_caption",
            field=models.CharField(
                blank=True,
                help_text="Write caption for the image in less than 500 characters",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testprogramtopic",
            name="topic_detail_second_video_embed_source",
            field=models.CharField(
                blank=True,
                help_text="Write the source of the video you want to embed. See the 'src' under iframe tag",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testprogramtopic",
            name="topic_detail_third_img_caption",
            field=models.CharField(
                blank=True,
                help_text="Write caption for the image in less than 500 characters",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testprogramtopic",
            name="topic_detail_third_video_embed_source",
            field=models.CharField(
                blank=True,
                help_text="Write the source of the video you want to embed. See the 'src' under iframe tag",
                max_length=200,
                null=True,
            ),
        ),
    ]
