# Generated by Django 4.1.7 on 2024-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_testprogram_priority_in_major_programs_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Trainer Name, along with academic qualification')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Affiliation')),
                ('social_link', models.CharField(max_length=200)),
                ('social_flag', models.CharField(choices=[('LI', 'LinkedIn'), ('FB', 'Facebook'), ('EM', 'Email')], max_length=2)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Order in Trainers List')),
                ('trainer_image', models.ImageField(upload_to='images/trainers ')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='testprogram',
            name='priority_in_major_programs_list',
            field=models.IntegerField(choices=[(0, 'Do not display on homepage'), (1, 'Display in third column'), (2, 'Display in second column'), (3, 'Display in first column')], default=0, help_text="Choose 0 if you don't want this program to display in homepage, else choose 1, 2, or 3 priority"),
        ),
        migrations.AlterField(
            model_name='testprogram',
            name='priority_in_programs_list',
            field=models.IntegerField(default=0, help_text='0 means lowest priority'),
        ),
        migrations.AlterField(
            model_name='testprogram',
            name='time_duration',
            field=models.CharField(help_text="Program Duration, For instance, 'Every Saturday, 1 hour, ...", max_length=100),
        ),
        migrations.AlterField(
            model_name='testprogramtopic',
            name='topic_detail_first_video_embed_source',
            field=models.CharField(blank=True, help_text="Write the source of the video you want to embed. See the 'src' under iframe tag. Looks like: https://www.youtube.com/embed/sl18__huoXI?si=k0ZoEVYVihc-E9Pn ", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testprogramtopic',
            name='topic_detail_second_video_embed_source',
            field=models.CharField(blank=True, help_text="Write the source of the video you want to embed. See the 'src' under iframe tag. Looks like: https://www.youtube.com/embed/sl18__huoXI?si=k0ZoEVYVihc-E9Pn ", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testprogramtopic',
            name='topic_detail_third_video_embed_source',
            field=models.CharField(blank=True, help_text="Write the source of the video you want to embed. See the 'src' under iframe tag. Looks like: https://www.youtube.com/embed/sl18__huoXI?si=k0ZoEVYVihc-E9Pn ", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testprogramtopic',
            name='topic_order',
            field=models.IntegerField(blank=True, default=0, help_text='1 to display this topic content on the first place, and similarly, 2 for second, 3 for third, and soon.'),
        ),
    ]
