# Generated by Django 4.1.7 on 2024-06-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainerslist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTrainingTrainers2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Trainer Name, along with academic qualification')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Affiliation')),
                ('social_link', models.CharField(max_length=200)),
                ('social_flag', models.CharField(choices=[('LI', 'LinkedIn'), ('FB', 'Facebook'), ('EM', 'Email')], max_length=2)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Order in Trainers List')),
                ('trainer_image', models.ImageField(upload_to='images/rt_trainers_2023')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='TrainersList',
        ),
    ]
