# Generated by Django 4.1.7 on 2024-06-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_researchtrainingtrainers2024_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTrainingMentors2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mentors Name, along with academic qualification')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Affiliation')),
                ('social_link', models.CharField(max_length=200)),
                ('social_flag', models.CharField(choices=[('LI', 'LinkedIn'), ('FB', 'Facebook'), ('EM', 'Email')], max_length=2)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Order in Mentors List')),
                ('trainer_image', models.ImageField(upload_to='images/rt_2023/rt_mentors__2023')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTrainingOrganizers2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Organizer Name')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Order in Organizers List')),
                ('trainer_image', models.ImageField(upload_to='images/rt_2023/rt_organizers__2023')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='researchtrainingtrainers2023',
            name='trainer_image',
            field=models.ImageField(upload_to='images/rt_2023/rt_trainers_2023'),
        ),
        migrations.AlterField(
            model_name='researchtrainingtrainers2024',
            name='trainer_image',
            field=models.ImageField(upload_to='images/rt_trainers_2024'),
        ),
    ]
