# Generated by Django 5.1 on 2024-08-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_researchtrainingtestimonials2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('social_medium_1', models.CharField(choices=[('LI', 'LinkedIn'), ('FB', 'Facebook'), ('EM', 'Email')], max_length=2)),
                ('social_medium_1_link', models.CharField(max_length=200)),
                ('social_medium_2', models.CharField(choices=[('LI', 'LinkedIn'), ('FB', 'Facebook'), ('EM', 'Email')], max_length=2)),
                ('social_medium_2_link', models.CharField(max_length=200)),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Order in Core Team List')),
                ('image', models.ImageField(upload_to='images/coreteam')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
