# Generated by Django 5.1 on 2024-08-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_coreteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Program Name')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('commence_date', models.DateField(verbose_name='Program Commence Data')),
                ('learn_more_link', models.URLField(blank=True, null=True, verbose_name='Link to Learn More')),
                ('featured_image', models.ImageField(blank=True, default='default/upcoming_program_image.png', null=True, upload_to='images/upcoming_programs')),
            ],
            options={
                'ordering': ['commence_date', 'published_date'],
            },
        ),
    ]
