# Generated by Django 5.1 on 2024-08-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_upcomingprograms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingprograms',
            name='commence_date',
            field=models.DateField(verbose_name='Program Commence Date'),
        ),
        migrations.AlterField(
            model_name='upcomingprograms',
            name='featured_image',
            field=models.ImageField(blank=True, default='default/upcoming_program_image.jpg', upload_to='images/upcoming_programs'),
        ),
    ]
