# Generated by Django 5.1 on 2024-08-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_upcomingprograms_commence_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingprograms',
            name='featured_image',
            field=models.ImageField(default='default/upcoming_program_image.jpg', upload_to='images/upcoming_programs'),
        ),
    ]
