# Generated by Django 5.1 on 2024-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_upcomingprograms_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_text', models.CharField(max_length=200, verbose_name='Descriptive text')),
                ('counts', models.PositiveIntegerField(verbose_name='Total Counts')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Order in Counts Section')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
