# Generated by Django 5.1 on 2024-08-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_upcomingprograms_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingprograms',
            name='featured_image',
            field=models.ImageField(default='default/upcoming_program_image.jpg', upload_to='images/upcoming_programs'),
        ),
    ]
