# Generated by Django 5.1 on 2024-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_upcomingprograms_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingprograms',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name="Program End Date (Leave blank if it's one day program)"),
        ),
    ]
