# Generated by Django 5.1 on 2024-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_upcomingprograms_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingprograms',
            name='commence_date',
            field=models.DateTimeField(verbose_name='Program Commence DateTime'),
        ),
        migrations.AlterField(
            model_name='upcomingprograms',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Program End DateTime (Leave blank if it's one day program)"),
        ),
    ]
