# Generated by Django 5.1 on 2024-08-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_upcomingprograms_commence_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingprograms',
            name='end_date',
            field=models.DateTimeField(verbose_name='Program End DateTime'),
        ),
    ]
