# Generated by Django 5.1 on 2024-08-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_homefeaturedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeaturedimage',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
