# Generated by Django 5.1 on 2024-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_newslettermailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='query_solved',
            field=models.BooleanField(default=False),
        ),
    ]
