# Generated by Django 5.1 on 2024-08-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTrainingTestimonials2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Order in Testimonials List')),
                ('image', models.ImageField(upload_to='images/rt_2024/rt_testimonials_2024')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
