# Generated by Django 5.1 on 2024-08-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_researchtrainingtestimonials2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testprogram',
            options={'verbose_name': 'Our Program', 'verbose_name_plural': 'Our Programs'},
        ),
        migrations.AlterModelOptions(
            name='testprogramtopic',
            options={'verbose_name': 'ProgramTopic', 'verbose_name_plural': 'ProgramTopics'},
        ),
        migrations.AddField(
            model_name='testprogram',
            name='google_form_link',
            field=models.URLField(blank=True, help_text='Google Form Link if somebody wants to be a part of this program', null=True),
        ),
        migrations.AlterField(
            model_name='programs',
            name='featured_image',
            field=models.ImageField(blank=True, default='default/no_image.jpg', null=True, upload_to='images/our_programs/featured_images'),
        ),
        migrations.AlterField(
            model_name='testprogram',
            name='program_featured_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/our_programs/featured_images'),
        ),
    ]
