# Generated by Django 4.1.7 on 2023-03-14 10:14

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('author_icon', models.ImageField(blank=True, default='default/no_image.jpg', null=True, upload_to='images/test_uploads/')),
                ('mail', models.EmailField(max_length=200)),
                ('joined_date', models.DateField()),
                ('priority', models.IntegerField(default=0, validators=[blog.models.validate_if_between_1_10])),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Blog Title')),
                ('body', models.TextField(default='Type here...')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=0, validators=[blog.models.validate_if_between_1_10])),
                ('featured_image', models.ImageField(blank=True, default='default/no_image.jpg', null=True, upload_to='images/test_uploads/')),
                ('slug', models.SlugField(max_length=600, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.authors')),
            ],
        ),
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(default='Here goes your Comments...')),
                ('date', models.DateField(auto_now_add=True)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs')),
            ],
        ),
    ]
