# Generated by Django 4.1.7 on 2023-03-25 12:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='priority',
            new_name='blog_priority',
        ),
        migrations.AddField(
            model_name='blogs',
            name='trending_priority',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[blog.models.validate_if_between_1_4]),
        ),
    ]
