# Generated by Django 4.1.7 on 2023-03-25 12:26

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_priority_blogs_blog_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='trending_priority',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, validators=[blog.models.validate_if_between_1_4]),
        ),
    ]
