# Generated by Django 4.1.7 on 2023-03-25 14:31

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogs_trending_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='trending_priority',
            field=models.IntegerField(blank=True, default=0, validators=[blog.models.validate_if_between_1_4]),
        ),
    ]
