# Generated by Django 4.1.7 on 2023-03-25 15:47

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_trending_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_priority',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='trending_priority',
        ),
        migrations.CreateModel(
            name='TrendingBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(unique=True, validators=[blog.models.validate_if_between_1_4])),
                ('Blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs')),
            ],
        ),
    ]
